(cl:in-package syropod_highlevel_controller-msg)
(cl:export '(HEADER-VAL
          HEADER
          NAME-VAL
          NAME
          WALKER_TIP_POSE-VAL
          WALKER_TIP_POSE
          TARGET_TIP_POSE-VAL
          TARGET_TIP_POSE
          POSER_TIP_POSE-VAL
          POSER_TIP_POSE
          MODEL_TIP_POSE-VAL
          MODEL_TIP_POSE
          ACTUAL_TIP_POSE-VAL
          ACTUAL_TIP_POSE
          MODEL_TIP_VELOCITY-VAL
          MODEL_TIP_VELOCITY
          JOINT_POSITIONS-VAL
          JOINT_POSITIONS
          JOINT_VELOCITIES-VAL
          JOINT_VELOCITIES
          JOINT_EFFORTS-VAL
          JOINT_EFFORTS
          STANCE_PROGRESS-VAL
          STANCE_PROGRESS
          SWING_PROGRESS-VAL
          SWING_PROGRESS
          TIME_TO_SWING_END-VAL
          TIME_TO_SWING_END
          POSE_DELTA-VAL
          POSE_DELTA
          AUTO_POSE-VAL
          AUTO_POSE
          TIP_FORCE-VAL
          TIP_FORCE
          ADMITTANCE_DELTA-VAL
          ADMITTANCE_DELTA
          VIRTUAL_STIFFNESS-VAL
          VIRTUAL_STIFFNESS
))