// Generated by gencpp from file syropod_remote/AndroidSensor.msg
// DO NOT EDIT!


#ifndef SYROPOD_REMOTE_MESSAGE_ANDROIDSENSOR_H
#define SYROPOD_REMOTE_MESSAGE_ANDROIDSENSOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <std_msgs/Bool.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Int8.h>
#include <std_msgs/Int8.h>
#include <geometry_msgs/Point.h>

namespace syropod_remote
{
template <class ContainerAllocator>
struct AndroidSensor_
{
  typedef AndroidSensor_<ContainerAllocator> Type;

  AndroidSensor_()
    : header()
    , id_name()
    , override_priority_interface()
    , orientation()
    , relative_compass()
    , robot_state()
    , posing_mode()
    , control_axis()  {
    }
  AndroidSensor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id_name(_alloc)
    , override_priority_interface(_alloc)
    , orientation(_alloc)
    , relative_compass(_alloc)
    , robot_state(_alloc)
    , posing_mode(_alloc)
    , control_axis(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::String_<ContainerAllocator>  _id_name_type;
  _id_name_type id_name;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _override_priority_interface_type;
  _override_priority_interface_type override_priority_interface;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _relative_compass_type;
  _relative_compass_type relative_compass;

   typedef  ::std_msgs::Int8_<ContainerAllocator>  _robot_state_type;
  _robot_state_type robot_state;

   typedef  ::std_msgs::Int8_<ContainerAllocator>  _posing_mode_type;
  _posing_mode_type posing_mode;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _control_axis_type;
  _control_axis_type control_axis;





  typedef boost::shared_ptr< ::syropod_remote::AndroidSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::syropod_remote::AndroidSensor_<ContainerAllocator> const> ConstPtr;

}; // struct AndroidSensor_

typedef ::syropod_remote::AndroidSensor_<std::allocator<void> > AndroidSensor;

typedef boost::shared_ptr< ::syropod_remote::AndroidSensor > AndroidSensorPtr;
typedef boost::shared_ptr< ::syropod_remote::AndroidSensor const> AndroidSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::syropod_remote::AndroidSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::syropod_remote::AndroidSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::syropod_remote::AndroidSensor_<ContainerAllocator1> & lhs, const ::syropod_remote::AndroidSensor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id_name == rhs.id_name &&
    lhs.override_priority_interface == rhs.override_priority_interface &&
    lhs.orientation == rhs.orientation &&
    lhs.relative_compass == rhs.relative_compass &&
    lhs.robot_state == rhs.robot_state &&
    lhs.posing_mode == rhs.posing_mode &&
    lhs.control_axis == rhs.control_axis;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::syropod_remote::AndroidSensor_<ContainerAllocator1> & lhs, const ::syropod_remote::AndroidSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace syropod_remote

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::syropod_remote::AndroidSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::syropod_remote::AndroidSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::syropod_remote::AndroidSensor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05a22ff6b1072fe74d2077e0d442d058";
  }

  static const char* value(const ::syropod_remote::AndroidSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05a22ff6b1072fe7ULL;
  static const uint64_t static_value2 = 0x4d2077e0d442d058ULL;
};

template<class ContainerAllocator>
struct DataType< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "syropod_remote/AndroidSensor";
  }

  static const char* value(const ::syropod_remote::AndroidSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/String id_name\n"
"std_msgs/Bool override_priority_interface\n"
"geometry_msgs/Point orientation\n"
"std_msgs/Float64 relative_compass\n"
"std_msgs/Int8 robot_state\n"
"std_msgs/Int8 posing_mode\n"
"geometry_msgs/Point control_axis\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
;
  }

  static const char* value(const ::syropod_remote::AndroidSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id_name);
      stream.next(m.override_priority_interface);
      stream.next(m.orientation);
      stream.next(m.relative_compass);
      stream.next(m.robot_state);
      stream.next(m.posing_mode);
      stream.next(m.control_axis);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AndroidSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::syropod_remote::AndroidSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::syropod_remote::AndroidSensor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.id_name);
    s << indent << "override_priority_interface: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.override_priority_interface);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "relative_compass: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.relative_compass);
    s << indent << "robot_state: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_state);
    s << indent << "posing_mode: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.posing_mode);
    s << indent << "control_axis: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.control_axis);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYROPOD_REMOTE_MESSAGE_ANDROIDSENSOR_H
