// Generated by gencpp from file syropod_highlevel_controller/TargetTipPose.msg
// DO NOT EDIT!


#ifndef SYROPOD_HIGHLEVEL_CONTROLLER_MESSAGE_TARGETTIPPOSE_H
#define SYROPOD_HIGHLEVEL_CONTROLLER_MESSAGE_TARGETTIPPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace syropod_highlevel_controller
{
template <class ContainerAllocator>
struct TargetTipPose_
{
  typedef TargetTipPose_<ContainerAllocator> Type;

  TargetTipPose_()
    : header()
    , name()
    , target()
    , stance()
    , swing_clearance()  {
    }
  TargetTipPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , target(_alloc)
    , stance(_alloc)
    , swing_clearance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _target_type;
  _target_type target;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _stance_type;
  _stance_type stance;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _swing_clearance_type;
  _swing_clearance_type swing_clearance;





  typedef boost::shared_ptr< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> const> ConstPtr;

}; // struct TargetTipPose_

typedef ::syropod_highlevel_controller::TargetTipPose_<std::allocator<void> > TargetTipPose;

typedef boost::shared_ptr< ::syropod_highlevel_controller::TargetTipPose > TargetTipPosePtr;
typedef boost::shared_ptr< ::syropod_highlevel_controller::TargetTipPose const> TargetTipPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator1> & lhs, const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.target == rhs.target &&
    lhs.stance == rhs.stance &&
    lhs.swing_clearance == rhs.swing_clearance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator1> & lhs, const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace syropod_highlevel_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05c537cc093e23228ee76fae952f2b3e";
  }

  static const char* value(const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05c537cc093e2322ULL;
  static const uint64_t static_value2 = 0x8ee76fae952f2b3eULL;
};

template<class ContainerAllocator>
struct DataType< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "syropod_highlevel_controller/TargetTipPose";
  }

  static const char* value(const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string[] name\n"
"geometry_msgs/PoseStamped[] target\n"
"geometry_msgs/PoseStamped[] stance\n"
"float64[] swing_clearance\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.target);
      stream.next(m.stance);
      stream.next(m.swing_clearance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetTipPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::syropod_highlevel_controller::TargetTipPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "target[]" << std::endl;
    for (size_t i = 0; i < v.target.size(); ++i)
    {
      s << indent << "  target[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.target[i]);
    }
    s << indent << "stance[]" << std::endl;
    for (size_t i = 0; i < v.stance.size(); ++i)
    {
      s << indent << "  stance[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.stance[i]);
    }
    s << indent << "swing_clearance[]" << std::endl;
    for (size_t i = 0; i < v.swing_clearance.size(); ++i)
    {
      s << indent << "  swing_clearance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.swing_clearance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYROPOD_HIGHLEVEL_CONTROLLER_MESSAGE_TARGETTIPPOSE_H
