# The obstacle data
uint32 id # the id of the obstacle 
string name # the name/label of the obstacle 
float64 x # x coordinate of the obstacle's centroid
float64 y # y coordinate of the obstacle's centroid
float64 z # z coordinate of the obstacle's centroid
float32 radius # radius of the object (optional way to describe its size)
float32[] verticesX # x coordinates of obstacle's vertices (optional way to describe its size and shape)
float32[] verticesY # y coordinates of obstacle's vertices (optional way to describe its size and shape)
float32[] verticesZ # z coordinates of obstacle's vertices (optional way to describe its size and shape)
